# Generated by Django 5.0.7 on 2024-07-30 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_id', models.IntegerField()),
                ('create_user_id', models.IntegerField()),
                ('time', models.CharField(max_length=512)),
                ('content', models.CharField(max_length=512)),
            ],
        ),
    ]
