# Generated by Django 5.0.7 on 2024-07-28 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=128)),
                ('studentId', models.CharField(default=str, max_length=32)),
                ('groups', models.JSONField(default=[1])),
                ('problems', models.JSONField(default=list)),
                ('problemGroups', models.JSONField(default=list)),
                ('head', models.ImageField(default='static/img/default.jpg', upload_to='static/img/')),
                ('log', models.JSONField(default=list)),
                ('problemlog', models.JSONField(default=list)),
                ('token', models.CharField(max_length=512)),
            ],
        ),
    ]
